using FellowOakDicom;
using FellowOakDicom.Imaging;
using FellowOakDicom.IO.Buffer;
using MyDicomViewer.Core.Imaging;

namespace MyDicomViewer.Core.Ai;

/// <summary>
/// AI スクリーニングの結果を DICOM（Secondary Capture: 二次取込画像）として書き出す。
/// 元画像にヒートマップを重ねたカラー画像を、同じ検査（Study）の新しいシリーズとして作るので、
/// 一般的な PACS やビューアでも元画像と並べて表示できる。
/// </summary>
public static class AiResultExporter
{
    public const string SeriesDescription = "AI Pneumonia Screening (research use only)";
    public const int ResultSeriesNumber = 9001;

    /// <summary>患者・検査の情報として元画像から引き継ぐタグ（すべて文字列型）</summary>
    private static readonly DicomTag[] InheritedTags =
    {
        DicomTag.PatientName, DicomTag.PatientID, DicomTag.PatientBirthDate, DicomTag.PatientSex,
        DicomTag.StudyInstanceUID, DicomTag.StudyDate, DicomTag.StudyTime, DicomTag.StudyID,
        DicomTag.AccessionNumber, DicomTag.ReferringPhysicianName, DicomTag.StudyDescription,
    };

    /// <summary>
    /// 表示中と同じ濃度設定（ウィンドウ）でグレースケール化し、ヒートマップを重ねた RGB 画像を作る。
    /// 大きな画像は長辺 maxSide に縮小する。
    /// </summary>
    public static (byte[] Rgb, int Width, int Height) ComposeOverlay(
        DicomDataset source, PneumoniaResult result, double windowCenter, double windowWidth,
        double heatmapOpacity = 0.6, int maxSide = 2048)
    {
        var (values, width, height, invert) = PneumoniaPreprocessor.ReadPixels(source);

        double scale = Math.Min(1.0, (double)maxSide / Math.Max(width, height));
        int w = Math.Max(1, (int)Math.Round(width * scale));
        int h = Math.Max(1, (int)Math.Round(height * scale));
        float[] resized = (w == width && h == height) ? values : ImageMath.Resize(values, width, height, w, h);

        byte[] gray = ImageMath.ApplyWindow(resized, windowCenter, windowWidth, invert);
        var heatmap = HeatmapRenderer.Render(result.Cam, result.CamSize, w, h, maxSide: Math.Max(w, h));

        var rgb = new byte[w * h * 3];
        for (int i = 0; i < w * h; i++)
        {
            double alpha = heatmap.Bgra[i * 4 + 3] / 255.0 * heatmapOpacity;
            double g = gray[i];
            rgb[i * 3 + 0] = Blend(g, heatmap.Bgra[i * 4 + 2], alpha); // R
            rgb[i * 3 + 1] = Blend(g, heatmap.Bgra[i * 4 + 1], alpha); // G
            rgb[i * 3 + 2] = Blend(g, heatmap.Bgra[i * 4 + 0], alpha); // B
        }
        return (rgb, w, h);
    }

    /// <summary>RGB 画像から Secondary Capture の DICOM データセットを作る</summary>
    public static DicomDataset CreateSecondaryCapture(
        DicomDataset source, byte[] rgb, int width, int height, PneumoniaResult result, string modelName, string softwareVersion)
    {
        if (rgb.Length != width * height * 3) throw new ArgumentException("RGB の画素数が画像サイズと一致しません。", nameof(rgb));

        var now = DateTime.Now;
        var ds = new DicomDataset(DicomTransferSyntax.ExplicitVRLittleEndian);

        foreach (var tag in InheritedTags)
        {
            if (source.Contains(tag)) ds.AddOrUpdate(tag, source.GetString(tag));
        }
        if (!ds.Contains(DicomTag.StudyInstanceUID)) ds.AddOrUpdate(DicomTag.StudyInstanceUID, DicomUIDGenerator.GenerateDerivedFromUUID());

        // ---- SOP 共通・シリーズ・装置
        ds.AddOrUpdate(DicomTag.SOPClassUID, DicomUID.SecondaryCaptureImageStorage);
        ds.AddOrUpdate(DicomTag.SOPInstanceUID, DicomUIDGenerator.GenerateDerivedFromUUID());
        ds.AddOrUpdate(DicomTag.SeriesInstanceUID, DicomUIDGenerator.GenerateDerivedFromUUID());
        ds.AddOrUpdate(DicomTag.Modality, "OT");
        ds.AddOrUpdate(DicomTag.SeriesNumber, ResultSeriesNumber);
        ds.AddOrUpdate(DicomTag.InstanceNumber, 1);
        ds.AddOrUpdate(DicomTag.SeriesDescription, SeriesDescription);
        ds.AddOrUpdate(DicomTag.ConversionType, "WSD"); // Workstation
        ds.AddOrUpdate(DicomTag.ImageType, "DERIVED", "SECONDARY");
        ds.AddOrUpdate(DicomTag.ContentDate, now.ToString("yyyyMMdd"));
        ds.AddOrUpdate(DicomTag.ContentTime, now.ToString("HHmmss"));
        ds.AddOrUpdate(DicomTag.Manufacturer, "MyDicomViewer");
        ds.AddOrUpdate(DicomTag.SoftwareVersions, softwareVersion);
        ds.AddOrUpdate(DicomTag.PatientOrientation, string.Empty);
        ds.AddOrUpdate(DicomTag.BurnedInAnnotation, "YES");

        // ---- AI の結果（どの元画像から、どのモデルで、どんな結果か）
        ds.AddOrUpdate(DicomTag.ImageComments, BuildComment(result, modelName));
        ds.AddOrUpdate(DicomTag.DerivationDescription,
            "Grad-CAM heatmap overlay generated by an on-device ONNX model. Research use only - not for diagnosis.");
        if (source.Contains(DicomTag.SOPInstanceUID) && source.Contains(DicomTag.SOPClassUID))
        {
            ds.Add(new DicomSequence(DicomTag.SourceImageSequence, new DicomDataset
            {
                { DicomTag.ReferencedSOPClassUID, source.GetString(DicomTag.SOPClassUID) },
                { DicomTag.ReferencedSOPInstanceUID, source.GetString(DicomTag.SOPInstanceUID) },
            }));
        }

        // ---- 画像（8bit RGB）
        ds.AddOrUpdate(DicomTag.SamplesPerPixel, (ushort)3);
        ds.AddOrUpdate(DicomTag.PhotometricInterpretation, PhotometricInterpretation.Rgb.Value);
        ds.AddOrUpdate(DicomTag.PlanarConfiguration, (ushort)0);
        ds.AddOrUpdate(DicomTag.Rows, (ushort)height);
        ds.AddOrUpdate(DicomTag.Columns, (ushort)width);
        ds.AddOrUpdate(DicomTag.BitsAllocated, (ushort)8);
        ds.AddOrUpdate(DicomTag.BitsStored, (ushort)8);
        ds.AddOrUpdate(DicomTag.HighBit, (ushort)7);
        ds.AddOrUpdate(DicomTag.PixelRepresentation, (ushort)0);

        var pixelData = DicomPixelData.Create(ds, true);
        pixelData.AddFrame(new MemoryByteBuffer(rgb));
        return ds;
    }

    internal static string BuildComment(PneumoniaResult result, string modelName) =>
        $"AI pneumonia screening: probability {result.Probability:F3}, threshold {result.Threshold:F3}, " +
        $"result {(result.IsPositive ? "POSITIVE (findings suggestive of pneumonia)" : "NEGATIVE")}. " +
        $"Model: {modelName}. Research use only - not for diagnosis.";

    private static byte Blend(double gray, byte color, double alpha) =>
        (byte)Math.Round(gray * (1 - alpha) + color * alpha);
}
